
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QThread
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QVBoxLayout, QPushButton
from PyQt5.QtGui import QPixmap, QIcon
from pyqtlet import L, MapWidget


class Labels(QWidget):
    def __init__(self):
        super().__init__()
        self.resize(1024, 600)
        self.degerYukseklik = 20
        self.degerAralik = 10
        #self.setWindowFlags(Qt.FramelessWindowHint)
        self.mapWidget = MapWidget()
        self.layout = QVBoxLayout()
        self.layout.addWidget(self.mapWidget)
        self.layout.setContentsMargins(0,0,0,0)
        self.setLayout(self.layout)
        self.font = QtGui.QFont()
        self.font.setPointSize(15)
        self.font10 = QtGui.QFont()
        self.font10.setPointSize(10)
        self.LabelBos = QLabel(self)
        self.LabelBos1 = QLabel(self)
        self.LabelBos3 = QLabel(self)

        self.LabelYukseklik = QLabel(self)
        self.LabelBatarya = QLabel(self)
        self.LabelDistance = QLabel(self)
        self.LabelHiz = QLabel(self)
        self.LabelUydu = QLabel(self)
        self.LabelUcusSuresi = QLabel(self)
        self.LabelKalanSure = QLabel(self)
        self.LabelArm = QLabel(self)
        self.LabelMode = QLabel(self)
        self.butonGorev = QPushButton("görev", self)
        self.butonGorev.setGeometry(0, 510, 80, 40)

        self.uyduPng = QPixmap('png/uydu.png')
        self.pil1Png = QPixmap('png/pil1.png')
        self.pil2Png = QPixmap('png/pil2.png')
        self.pil3Png = QPixmap('png/pil3.png')
        self.pil4Png = QPixmap('png/pil4.png')
        self.pil5Png = QPixmap('png/pil5.png')
        self.pilDoluPng = QPixmap('png/pildolu.png')
        self.KumSaatPng = QPixmap('png/kumSaati.png')
        self.HizPng = QPixmap('png/hız.png')
        self.yukseklikPng = QPixmap('png/yukseklik.png')
        self.evPng = QPixmap('png/uzaklık.png')
        self.saatPng = QPixmap('png/saat.png')
        self.logoPng = QPixmap('png/logo.png')


        self.pilResim = QLabel(self)
        self.pilResim.setPixmap(self.pil5Png)
        self.pilResim.setGeometry(905, 10, 70, 32)
        self.uydu = QLabel(self)
        self.uydu.setPixmap(self.uyduPng)
        self.uydu.setGeometry(835, 10, 40, 32)
        self.KumSaat = QLabel(self)
        self.KumSaat.setPixmap(self.KumSaatPng)
        self.KumSaat.setGeometry(525, 0, 50, 50)
        self.HizIcon = QLabel(self)
        self.HizIcon.setPixmap(self.HizPng)
        self.HizIcon.setGeometry(10, 550, 45, 45)
        self.YukseklikIcon = QLabel(self)
        self.YukseklikIcon.setPixmap(self.yukseklikPng)
        self.YukseklikIcon.setGeometry(190, 555, 45, 45)
        self.EvIcon = QLabel(self)
        self.EvIcon.setPixmap(self.evPng)
        self.EvIcon.setGeometry(350, 555, 300, 45)
        self.SaatIcon = QLabel(self)
        self.SaatIcon.setPixmap(self.saatPng)
        self.SaatIcon.setGeometry(590, 552, 45, 45)

        self.flyshark = QLabel(self)
        self.flyshark.setPixmap(self.logoPng)
        self.flyshark.setGeometry(770, 479, 240, 121)

        self.artiYukseklik = QPushButton(self)
        self.artiYukseklik.setIcon(QIcon('png/arti.png'))
        self.artiYukseklik.setGeometry(950,60,48,50)
        self.artiYukseklik.setIconSize(QtCore.QSize(48, 50))
        self.artiYukseklik.setStyleSheet("border-radius: 25px;")
        self.artiYukseklik.clicked.connect(self.yuk_arti)
        self.eksiYukseklik = QPushButton(self)
        self.eksiYukseklik.setIcon(QIcon('png/eksi.png'))
        self.eksiYukseklik.setGeometry(880,60,49,50)
        self.eksiYukseklik.setIconSize(QtCore.QSize(49, 50))
        self.eksiYukseklik.setStyleSheet("border-radius: 25px;")
        self.eksiYukseklik.clicked.connect(self.yuk_eksi)
        self.eksiAralik = QPushButton(self)
        self.eksiAralik.setIcon(QIcon('png/eksi.png'))
        self.eksiAralik.setGeometry(880,120,49,50)
        self.eksiAralik.setIconSize(QtCore.QSize(49, 50))
        self.eksiAralik.setStyleSheet("border-radius: 25px;")
        self.eksiAralik.clicked.connect(self.ara_eksi)
        self.artiAralik = QPushButton(self)
        self.artiAralik.setIcon(QIcon('png/arti.png'))
        self.artiAralik.setGeometry(950,120,48,50)
        self.artiAralik.setIconSize(QtCore.QSize(48, 50))
        self.artiAralik.setStyleSheet("border-radius: 25px;")
        self.artiAralik.clicked.connect(self.ara_arti)



        self.LabelYukseklik.setText("m")
        self.LabelBatarya.setText("%35")
        self.LabelDistance.setText("m")
        self.LabelHiz.setText("m/s")
        self.LabelUydu.setText("0")
        self.LabelUcusSuresi.setText(" dk")
        self.LabelKalanSure.setText("dk")
        self.LabelArm.setText("BAĞLANTI YOK")
        self.LabelMode.setText("GUIDED")

        self.LabelBos2 = QLabel(self)
        self.LabelBekle = QLabel(self)
        self.LabelBekle.setText("BAĞLANIYOR...")
        self.LabelBekle.setGeometry(375, 285, 200, 30)
        self.LabelBekle.setStyleSheet("color: White")
        self.LabelBekle.hide()

        self.LabelBos.setGeometry(0, 0, 1024, 50)
        self.LabelBos1.setGeometry(0, 550, 760, 50)
        self.LabelBos2.setGeometry(0, 0, 1024, 600)
        self.LabelBos3.setGeometry(724, 50, 300, 200)
        self.LabelBos2.hide()

        self.LabelBatarya.setGeometry(950, 10, 80, 30)
        self.LabelUydu.setGeometry(870, 0, 30, 20)
        self.LabelKalanSure.setGeometry(570, 10, 100, 30)
        self.LabelArm.setGeometry(280, 10, 235, 30)
        self.LabelMode.setGeometry(660, 10, 160, 30)

        self.LabelHiz.setGeometry(60, 560, 120, 30)
        self.LabelYukseklik.setGeometry(240, 560, 230, 30)
        self.LabelDistance.setGeometry(413, 550, 100, 30)
        self.LabelUcusSuresi.setGeometry(640, 560, 290, 30)

        self.LabelBos.setStyleSheet("background-color: rgba(0, 0, 0, 100)")
        self.LabelBos1.setStyleSheet("background-color: rgba(0, 0, 0, 100)")
        self.LabelBos2.setStyleSheet("background-color: rgba(0, 0, 0, 200)")
        self.LabelBos3.setStyleSheet("background-color: rgba(0, 0, 0, 100); border-radius: 25px;")
        self.LabelYukseklik.setStyleSheet(" color: white")
        self.LabelBatarya.setStyleSheet("color: white")
        self.LabelDistance.setStyleSheet("color: white")
        self.LabelHiz.setStyleSheet(" color: white")
        self.LabelUydu.setStyleSheet(" color: white")
        self.LabelUcusSuresi.setStyleSheet(" color: white")
        self.LabelKalanSure.setStyleSheet(" color: white")
        self.LabelArm.setStyleSheet(" color:  red")
        self.LabelMode.setStyleSheet(" color: rgb(255, 215, 0)")
        self.LabelYukseklik.setFont(self.font)
        self.LabelBatarya.setFont(self.font)
        self.LabelDistance.setFont(self.font)
        self.LabelHiz.setFont(self.font)
        self.LabelUcusSuresi.setFont(self.font)
        self.LabelKalanSure.setFont(self.font)
        self.LabelArm.setFont(self.font)
        self.LabelMode.setFont(self.font)
        self.LabelBekle.setFont(self.font)

        self.butonBitti = QPushButton("ÇİZ", self)
        self.butonBitti.setGeometry(830, 180, 80, 40)
        self.butonSil = QPushButton("SİL", self)
        self.butonSil.setGeometry(740, 180, 80, 40)
        self.butonYukle = QPushButton("YÜKLE", self)
        self.butonYukle.setGeometry(920, 180, 80, 40)

        self.butonBitti.setStyleSheet(" color: white; background-color: rgb(113, 113, 113); border-radius: 15px;")
        self.butonSil.setStyleSheet(" color: white; background-color: rgb(113, 113, 113); border-radius: 15px;")
        self.butonYukle.setStyleSheet(" color: white; background-color: rgb(113, 113, 113); border-radius: 15px;")
        self.butonGorev.setStyleSheet(" color: white; background-color: rgb(113, 113, 113); border-radius: 15px;")
        self.butonYukle.setFont(self.font10)
        self.butonSil.setFont(self.font10)
        self.butonBitti.setFont(self.font10)
        self.butonGorev.setFont(self.font10)


        self.yazi1 = QLabel(self)
        self.yazi1.setText("YÜKSEKLİK: "+ str(self.degerYukseklik))
        self.yazi1.setGeometry(740,70,130,30)
        self.yazi1.setFont(self.font10)
        self.yazi2 = QLabel(self)
        self.yazi2.setText("ARALIK: "+ str(self.degerAralik))
        self.yazi2.setGeometry(740, 130, 130, 30)
        self.yazi2.setFont(self.font10)
        self.yazi2.setStyleSheet(" color: white; background-color: blue; border-radius: 15px; ")
        self.yazi1.setStyleSheet(" color: white; background-color: blue; border-radius: 15px;")
        self.yazi2.setAlignment(Qt.AlignCenter)
        self.yazi1.setAlignment(Qt.AlignCenter)

        self.gizle()


    def yuk_arti(self):
        self.degerYukseklik+= 1
        self.yazi1.setText("YÜKSEKLİK: " + str(self.degerYukseklik))
    def yuk_eksi(self):
        self.degerYukseklik-= 1
        self.yazi1.setText("YÜKSEKLİK: " + str(self.degerYukseklik))
    def ara_arti(self):
        self.degerAralik+=1
        self.yazi2.setText("ARALIK: "+ str(self.degerAralik))
    def ara_eksi(self):
        self.degerAralik-=1
        self.yazi2.setText("ARALIK: "+ str(self.degerAralik))
    def goster(self):
        self.yazi2.show()
        self.yazi1.show()
        self.artiAralik.show()
        self.artiYukseklik.show()
        self.eksiAralik.show()
        self.eksiYukseklik.show()
        self.LabelBos3.show()
        self.butonSil.show()
        self.butonBitti.show()
        self.butonYukle.show()
    def gizle(self):
        self.butonSil.hide()
        self.butonBitti.hide()
        self.butonYukle.hide()
        self.yazi2.hide()
        self.yazi1.hide()
        self.artiAralik.hide()
        self.artiYukseklik.hide()
        self.eksiAralik.hide()
        self.eksiYukseklik.hide()
        self.LabelBos3.hide()