
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QThread
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QVBoxLayout, QPushButton, QSpinBox
from PyQt5.QtGui import QPixmap
from pyqtlet import L, MapWidget


class Labels(QWidget):
    def __init__(self):
        super().__init__()
        self.resize(1024, 600)
        #self.setWindowFlags(Qt.FramelessWindowHint)
        self.mapWidget = MapWidget()
        self.layout = QVBoxLayout()
        self.layout.addWidget(self.mapWidget)
        self.layout.setContentsMargins(0,0,0,0)
        self.setLayout(self.layout)
        self.font = QtGui.QFont()
        self.font.setPointSize(15)
        self.LabelBos = QLabel(self)
        self.LabelBos1 = QLabel(self)
        self.LabelYukseklik = QLabel(self)
        self.LabelBatarya = QLabel(self)
        self.LabelDistance = QLabel(self)
        self.LabelHiz = QLabel(self)
        self.LabelUydu = QLabel(self)
        self.LabelUcusSuresi = QLabel(self)
        self.LabelKalanSure = QLabel(self)
        self.LabelArm = QLabel(self)
        self.LabelMode = QLabel(self)
        self.butonGorev = QPushButton(self)
        self.butonGorev.setText("görev")
        self.butonGorev.setGeometry(0, 510, 80, 40)

        self.uyduPng = QPixmap('png/uydu.png')
        self.pil1Png = QPixmap('png/pil1.png')
        self.pil2Png = QPixmap('png/pil2.png')
        self.pil3Png = QPixmap('png/pil3.png')
        self.pil4Png = QPixmap('png/pil4.png')
        self.pil5Png = QPixmap('png/pil5.png')
        self.pilDoluPng = QPixmap('png/pildolu.png')
        self.KumSaatPng = QPixmap('png/kumSaati.png')
        self.HizPng = QPixmap('png/hız.png')
        self.yukseklikPng = QPixmap('png/yukseklik.png')
        self.evPng = QPixmap('png/uzaklık.png')
        self.saatPng = QPixmap('png/saat.png')
        self.logoPng = QPixmap('png/flyshark.png')

        self.pilResim = QLabel(self)
        self.pilResim.setPixmap(self.pil5Png)
        self.pilResim.setGeometry(850, 10, 70, 32)
        self.uydu = QLabel(self)
        self.uydu.setPixmap(self.uyduPng)
        self.uydu.setGeometry(795, 10, 40, 32)
        self.KumSaat = QLabel(self)
        self.KumSaat.setPixmap(self.KumSaatPng)
        self.KumSaat.setGeometry(485, 0, 50, 50)
        self.HizIcon = QLabel(self)
        self.HizIcon.setPixmap(self.HizPng)
        self.HizIcon.setGeometry(10, 550, 45, 45)
        self.YukseklikIcon = QLabel(self)
        self.YukseklikIcon.setPixmap(self.yukseklikPng)
        self.YukseklikIcon.setGeometry(190, 555, 45, 45)
        self.EvIcon = QLabel(self)
        self.EvIcon.setPixmap(self.evPng)
        self.EvIcon.setGeometry(350, 555, 300, 45)
        self.SaatIcon = QLabel(self)
        self.SaatIcon.setPixmap(self.saatPng)
        self.SaatIcon.setGeometry(590, 552, 45, 45)

        self.flyshark = QLabel(self)
        self.flyshark.setPixmap(self.logoPng)
        self.flyshark.setGeometry(15, 5, 260, 45)

        self.LabelYukseklik.setText("m")
        self.LabelBatarya.setText("%35")
        self.LabelDistance.setText("m")
        self.LabelHiz.setText("m/s")
        self.LabelUydu.setText("0")
        self.LabelUcusSuresi.setText(" dk")
        self.LabelKalanSure.setText("dk")
        self.LabelArm.setText("BAĞLANTI YOK")
        self.LabelMode.setText("GUIDED")

        self.LabelBos2 = QLabel(self)
        self.LabelBekle = QLabel(self)
        self.LabelBekle.setText("BAĞLANIYOR...")
        self.LabelBekle.setGeometry(375, 285, 200, 30)
        self.LabelBekle.setStyleSheet("color: White")
        self.LabelBekle.hide()

        self.LabelBos.setGeometry(0, 0, 1024, 50)
        self.LabelBos1.setGeometry(0, 550, 760, 50)
        self.LabelBos2.setGeometry(0, 0, 1024, 600)
        self.LabelBos2.hide()

        self.LabelBatarya.setGeometry(905, 10, 60, 30)
        self.LabelUydu.setGeometry(830, 0, 20, 20)
        self.LabelKalanSure.setGeometry(530, 10, 100, 30)
        self.LabelArm.setGeometry(280, 10, 170, 30)
        self.LabelMode.setGeometry(650, 10, 100, 30)

        self.LabelHiz.setGeometry(60, 560, 120, 30)
        self.LabelYukseklik.setGeometry(240, 560, 230, 30)
        self.LabelDistance.setGeometry(413, 550, 100, 30)
        self.LabelUcusSuresi.setGeometry(640, 560, 290, 30)

        self.LabelBos.setStyleSheet("background-color: rgba(0, 0, 0, 100)")
        self.LabelBos1.setStyleSheet("background-color: rgba(0, 0, 0, 100)")
        self.LabelBos2.setStyleSheet("background-color: rgba(0, 0, 0, 200)")
        self.LabelYukseklik.setStyleSheet(" color: white")
        self.LabelBatarya.setStyleSheet("color: white")
        self.LabelDistance.setStyleSheet("color: white")
        self.LabelHiz.setStyleSheet(" color: white")
        self.LabelUydu.setStyleSheet(" color: white")
        self.LabelUcusSuresi.setStyleSheet(" color: white")
        self.LabelKalanSure.setStyleSheet(" color: white")
        self.LabelArm.setStyleSheet(" color:  red")
        self.LabelMode.setStyleSheet(" color: rgb(255, 215, 0)")
        self.LabelYukseklik.setFont(self.font)
        self.LabelBatarya.setFont(self.font)
        self.LabelDistance.setFont(self.font)
        self.LabelHiz.setFont(self.font)
        # self.LabelUydu.setFont(self.font)
        self.LabelUcusSuresi.setFont(self.font)
        self.LabelKalanSure.setFont(self.font)
        self.LabelArm.setFont(self.font)
        self.LabelMode.setFont(self.font)
        self.LabelBekle.setFont(self.font)

        self.butonBitti = QPushButton(self)
        self.butonBitti.setText("bitti")
        self.butonBitti.setGeometry(0,50,60,40)
        self.butonBitti.hide()
        self.butonSil = QPushButton(self)
        self.butonSil.setText("sil")
        self.butonSil.setGeometry(60,50,60,40)
        self.butonSil.hide()
        self.spin = QSpinBox(self)
        self.spin.setGeometry(10,90,100,40)
        self.spin.setValue(10)
        self.spin.hide()
        self.butonYukle = QPushButton(self)
        self.butonYukle.setText("yukle")
        self.butonYukle.setGeometry(79, 510, 80, 40)
        self.butonYukle.hide()